"""PlatformIO pre-build script: stamp the git description into pf_version.h.

The firmware reports fw/git in its MQTT state doc and compares PF_VERSION against
the retained cmd/ota topic to decide whether to pull an update, so this needs to
change whenever the source does.
"""

import subprocess
from pathlib import Path

Import("env")  # noqa: F821  (injected by SCons)


def _git(*args, default="unknown"):
    try:
        return subprocess.check_output(("git",) + args, stderr=subprocess.DEVNULL,
                                       text=True).strip() or default
    except Exception:
        return default


version = _git("describe", "--tags", "--always", "--dirty", default="0.0.0-dev")
sha = _git("rev-parse", "--short", "HEAD", default="nogit")

header = Path(env.subst("$PROJECT_INCLUDE_DIR")) / "pf_version.h"  # noqa: F821
new = (
    "// Generated by tools/build_version.py. Do not edit; do not commit.\n"
    "#pragma once\n\n"
    f'#define PF_VERSION "{version}"\n'
    f'#define PF_GIT_SHA "{sha}"\n'
)

# Only rewrite when it changed, so we don't invalidate the whole build every time.
if not header.exists() or header.read_text() != new:
    header.write_text(new)
    print(f"pf_version.h -> {version} ({sha})")
